n = input('Sobre o que vc quer informacoes? ')
print('O tipo da variavel e ', type(n))
print('E alphanumerico? ', n.isalnum())
print('E alfabeto? ', n.isalpha())
print('E ascii? ', n.isascii())
print('E um digito? ', n.isdigit())
print('So possui minusculo? ', n.islower())
print('So possui maiusculo? ', n.isupper())
print('E um numero decimal? ', n.isdecimal())
print('E um identificador? ', n.isidentifier())
print('E um numero? ', n.isnumeric())
print('Pode ser printed? ', n.isprintable())
print('E um titulo? ', n.istitle())
print('E um espaco? ', n.isspace())
